smart-home-web/Components/BoolHeatmapViewComponent.cs
using AutoMapper;
using Infrastructure.Business.DTOs.ReportElements;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Components.ReportElements;
using smart_home_web.Models.ReportElements;
using System.Threading.Tasks;

namespace smart_home_web.Components
{
    public class BoolHeatmapViewComponent : BaseViewComponent
    {
        private readonly IReportElementManager _reportElementManager;
        private readonly IMapper _mapper;
        public BoolHeatmapViewComponent(IReportElementManager reportElementManager, IMapper mapper)
        {
            _reportElementManager = reportElementManager;
            _mapper = mapper;
        }
        public async Task<IViewComponentResult> InvokeAsync(int reportElementId)
        {
            BoolHeatmapDto boolHeatmapDto = await _reportElementManager.GetBoolHeatmapById(reportElementId);
            BoolHeatmapViewModel result = _mapper.Map<BoolHeatmapDto, BoolHeatmapViewModel>(boolHeatmapDto);

            return View("BoolHeatmap", result);
        }
    }
}

smart-home-web/Components/Others/DashboardCreateViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace smart_home_web.Components.Others
{
    public class DashboardCreateViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke() => View();
    }
}

smart-home-web/Components/Others/DashboardEditViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.Dashboard;

namespace smart_home_web.Components.Others
{
    public class DashboardEditViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke(EditDashboardViewModel model) => View(model);
    }
}

smart-home-web/Components/Others/DashboardElementViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.Dashboard;

namespace smart_home_web.Components.Others
{
    public class DashboardElementViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(DashboardViewModel model) => View(model);
    }
}

smart-home-web/Components/Others/HistoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.History;

namespace smart_home_web.Components.Others
{
    public class HistoryViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke(AllHistoriesViewModel model) => View(model);
    }
}

smart-home-web/Components/Others/ModalsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Components.Others
{
    public class ModalsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string name)
        {
            ViewBag.elementname = name;
            return View();
        }
    }
}

smart-home-web/Components/Others/PaginationViewComponent.cs
using Infrastructure.Business.DTOs;
using smart_home_web.Models;
using Microsoft.AspNetCore.Mvc;

namespace smart_home_web.Components.Others
{
    public class PaginationViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke(string controller, string action, FilterDto filterDTO)
        {
            PaginationViewModel model = new PaginationViewModel
            {
                controller = controller,
                action = action,
                filterDto = filterDTO
            };
            return View(model);
        }
    }
}

smart-home-web/Components/Others/SensorCreateViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.SensorViewModel;

namespace smart_home_web.Components.Others
{
    public class SensorCreateViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(CreateSensorViewModel model) => View(model);
    }
}

smart-home-web/Components/Others/SensorEditViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.SensorViewModel;

namespace smart_home_web.Components.Others
{
    public class SensorEditViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(EditSensorViewModel model) => View(model);
    }
}

smart-home-web/Components/Others/SensorElementViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.SensorViewModel;

namespace smart_home_web.Components.Others
{
    public class SensorElementViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(SensorViewModel model) => View(model);
    }
}

smart-home-web/Components/Others/SensorTypeCreateViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.SensorType;

namespace smart_home_web.Components.Others
{
    public class SensorTypeCreateViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(CreateSensorTypeViewModel model) => View(model);
    }
}

smart-home-web/Components/Others/SensorTypeEditViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.SensorType;

namespace smart_home_web.Components.Others
{
    public class SensorTypeEditViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(EditSensorTypeViewModel model) => View(model);
    }
}

smart-home-web/Components/Others/SensorTypeElementViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.SensorType;

namespace smart_home_web.Components.Others
{
    public class SensorTypeElementViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(SensorTypeViewModel model) => View(model);
    }
}

smart-home-web/Components/ReportElements/BaseViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Components.ReportElements
{
    public abstract class BaseViewComponent : ViewComponent
    {
        public int DashboardId { get; set; }
    }
}

smart-home-web/Components/ReportElements/ClockViewComponent.cs
using AutoMapper;
using Infrastructure.Business.DTOs.Dashboard;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.Dashboard;
using smart_home_web.Models.ReportElements;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Components.ReportElements
{
    public class ClockViewComponent : BaseViewComponent
    {
        private readonly IReportElementManager _reportElementManager;
        private readonly IMapper _mapper;
        public ClockViewComponent(IReportElementManager reportElementManager, IMapper mapper)
        {
            _reportElementManager = reportElementManager;
            _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync(int reportElementId)
        {
            ReportElementViewModel model = new ReportElementViewModel
            {
                Id = reportElementId
            };
            return View("Default", model);
        }
    }
}

smart-home-web/Components/ReportElements/ColumnRangeViewComponent.cs
using AutoMapper;
using Infrastructure.Business.DTOs.ReportElements;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.ReportElements;
using System.Threading.Tasks;

namespace smart_home_web.Components.ReportElements
{
    public class ColumnrangeViewComponent : BaseViewComponent
    {
        private readonly IReportElementManager _reportElementManager;
        private readonly IMapper _mapper;
        public ColumnrangeViewComponent(IReportElementManager reportElementManager, IMapper mapper)
        {
            _reportElementManager = reportElementManager;
            _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync(int reportElementId)
        {
            ReportElementDto columnRangeDTO = await _reportElementManager.GetColumnRangeById(reportElementId);
            ReportElementViewModel model = _mapper.Map<ReportElementDto, ReportElementViewModel>(columnRangeDTO);
            return View(model);
        }
    }
}

smart-home-web/Components/ReportElements/GaugeViewComponent.cs
using AutoMapper;
using Infrastructure.Business.DTOs.ReportElements;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.ReportElements;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Components.ReportElements
{
    public class GaugeViewComponent : BaseViewComponent
    {
        private readonly IReportElementManager _reportElementManager;
        private readonly IMapper _mapper;
        public GaugeViewComponent(IReportElementManager reportElementManager, IMapper mapper)
        {
            _reportElementManager = reportElementManager;
            _mapper = mapper;
        }
        public async Task<IViewComponentResult> InvokeAsync(int reportElementId)
        {
            GaugeDto gaugeDto = await _reportElementManager.GetGaugeById(reportElementId);
            GaugeViewModel result = _mapper.Map<GaugeDto, GaugeViewModel>(gaugeDto);
            return View(result);
        }
    }
}

smart-home-web/Components/ReportElements/HeatmapViewComponent.cs
using AutoMapper;
using Infrastructure.Business.DTOs.ReportElements;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.ReportElements;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Components.ReportElements
{
    public class HeatmapViewComponent : BaseViewComponent
    {
        private readonly IReportElementManager _reportElementManager;
        private readonly IMapper _mapper;
        public HeatmapViewComponent(IReportElementManager reportElementManager, IMapper mapper)
        {
            _reportElementManager = reportElementManager;
            _mapper = mapper;
        }
        public async Task<IViewComponentResult> InvokeAsync(int reportElementId)
        {
            HeatmapDto heatmapDto = await _reportElementManager.GetHeatmapById(reportElementId);
            HeatmapViewModel result = _mapper.Map<HeatmapDto, HeatmapViewModel>(heatmapDto);
            return View("Heatmap", result);
        }
    }
}

smart-home-web/Components/ReportElements/OnOffViewComponent.cs
using AutoMapper;
using Infrastructure.Business.DTOs.ReportElements;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.ReportElements;
using System.Threading.Tasks;

namespace smart_home_web.Components.ReportElements
{
    public class OnOffViewComponent : BaseViewComponent
    {
        private readonly IReportElementManager _reportElementManager;
        private readonly IMapper _mapper;
        public OnOffViewComponent(IReportElementManager reportElementManager, IMapper mapper)
        {
            _reportElementManager = reportElementManager;
            _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync(int reportElementId)
        {
            ReportElementDto onOff = await _reportElementManager.GetOnOffById(reportElementId);
            ReportElementViewModel result = _mapper.Map<ReportElementDto, ReportElementViewModel>(onOff);
            return View("OnOff", result);
        }
    }
}

smart-home-web/Components/ReportElements/StatusReportViewComponent.cs
using AutoMapper;
using Infrastructure.Business.DTOs.ReportElements;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.ReportElements;
using System.Threading.Tasks;

namespace smart_home_web.Components.ReportElements
{
    public class StatusReportViewComponent : BaseViewComponent
    {
        private readonly IReportElementManager _reportElementManager;
        private readonly IMapper _mapper;
        public StatusReportViewComponent(IReportElementManager reportElementManager, IMapper mapper)
        {
            _reportElementManager = reportElementManager;
            _mapper = mapper;
        }
        public async Task<IViewComponentResult> InvokeAsync(int reportElementId, string userid)
        {
            ReportElementDto element = await _reportElementManager.GetStatusReport(reportElementId, userid);
            return View(_mapper.Map<ReportElementDto, ReportElementViewModel>(element));
        }
    }
}

smart-home-web/Controllers/ReportElementController.cs
using System.Threading.Tasks;
using AutoMapper;
using Domain.Core.Model;
using Domain.Core.Model.Enums;
using Infrastructure.Business.DTOs.ReportElements;
using Infrastructure.Business.DTOs.Sensor;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models;
using smart_home_web.Models.ReportElements;

namespace smart_home_web.Controllers
{
	[Authorize]
	public class ReportElementController : Controller
    {
        private readonly IReportElementManager _reportElementManager;
        private readonly IMapper _mapper;
        private readonly UserManager<AppUser> _userManager;

        public ReportElementController(IReportElementManager reportElementManager, IMapper mapper,UserManager<AppUser> userManager)
        {
            _reportElementManager = reportElementManager;
            _mapper = mapper;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult CreateReportElement(int dashboardId)
        {
            CreateReportElementViewModel model = new CreateReportElementViewModel
            {
                DashboardId = dashboardId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateReportElement(CreateReportElementViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            string userId = _userManager.GetUserId(User);
            ReportElementDto reportElement = _mapper.Map<CreateReportElementViewModel, ReportElementDto>(model);
            await _reportElementManager.CreateReportElement(reportElement, userId);
            return RedirectToAction("Detail", "Dashboard", new { id = model.DashboardId});
        }

        [HttpGet]
        public async Task<IActionResult> EditReportElement(int id)
        {
            ReportElement reportElement = await _reportElementManager.GetById(id);
            if (reportElement == null)
                return NotFound();
            EditReportElementViewModel model = _mapper.Map<ReportElement, EditReportElementViewModel>(reportElement);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditReportElement(EditReportElementViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            ReportElementDto reportElement = _mapper.Map<EditReportElementViewModel, ReportElementDto>(model);
            await _reportElementManager.EditReportElement(reportElement);
            return RedirectToAction("Detail", "Dashboard", new { id = model.DashboardId });
        }

		[HttpPost]
		public async Task<IActionResult> DeleteReportElement(int id)
		{
			var reportElement = await _reportElementManager.GetById(id);
			await _reportElementManager.Delete(reportElement);
			return Ok();
		}

		[HttpPost]
		public async Task<IActionResult> LockReportElement(int id)
		{
			var reportElement = await _reportElementManager.GetById(id);
			await _reportElementManager.Lock(reportElement);
			return Ok();
		}
	}
}

smart-home-web/Views/Shared/Components/Timeseries/Default.cshtml
@using smart_home_web.Models.ReportElements
﻿@using Domain.Core.Model.Enums
@model ReportElementViewModel

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

@if (!Model.IsCorrect)
{
    <label class="control-label graph-label">There is no history measurement for @Model.SensorName.ToString() for that period of time. <a class="btn btn-success text-center" asp-controller="ReportElement" asp-action="EditReportElement" asp-route-id="@Model.Id"><i class="fas fa-cog"></i></a></label>
}
else
{
    <figure class="highcharts-figure">
        <div id=@("TimeSeries"+Model.Id.ToString()) data-save-sensorid="@Model.SensorId"></div>
    </figure>
}
<script>
    Highcharts.getJSON(
        'https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/usdeur.json',
        function (data) {

          Highcharts.chart('TimeSeries'+JSON.parse('@Html.Raw(Json.Serialize(@Model.Id.ToString()))'), {
              chart: {
                  zoomType: 'x',
                  height: 380
                },
                title: {
                    text: JSON.parse('@Html.Raw(Json.Serialize(@Model.SensorName))')                   
                },
                subtitle: {
                    text: document.ontouchstart === undefined ?
                        'Click and drag in the plot area to zoom in' : 'Pinch the chart to zoom in'
                },
                xAxis: {
                categories: JSON.parse('@Html.Raw(Json.Serialize(@Model.Milliseconds))'),
                labels: {
                    formatter: function () {
                        return new Date(this.value).toLocaleString();
                    }
                }
                },
                yAxis: {
                    title: {
                        text: JSON.parse('@Html.Raw(Json.Serialize(@Model.SensorType))') + ' ' + JSON.parse('@Html.Raw(Json.Serialize(@Model.MeasurementName))')
                    }
                },
                 tooltip: {
                formatter: function () {
                    var date = new Date(this.x).toLocaleString();
                    @switch (Model.MeasurementType)
                     {
                        case MeasurementType.Bool:

                            <text>
                            var values = JSON.parse('@Html.Raw(Json.Serialize(@Model.Values))')
                            var value = values[this.point.index] ? 'true':'false'
                            var result = '<b>' + date + '</b><br>' + this.series.name + ': <b>' + value + '</b><br>'
                            return result;
                            </text>
                            break;

                        default:
                            <text>
                            var result = '<b>' + date + '</b><br>' + this.series.name + ': <b>' + this.y + ' '
                            + JSON.parse('@Html.Raw(Json.Serialize(@Model.MeasurementName))') + '</b><br>'
                            return result;
                            </text>
                            break;
                     }
                 }
                },

                legend: {
                    enabled: false
                },
                plotOptions: {
                    area: {
                        fillColor: {
                            linearGradient: {
                                x1: 0,
                                y1: 0,
                                x2: 0,
                                y2: 1
                            },
                            stops: [
                                [0, Highcharts.getOptions().colors[0]],
                                [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                            ]
                        },
                        marker: {
                            radius: 2
                        },
                        lineWidth: 1,
                        states: {
                            hover: {
                                lineWidth: 1
                            }
                        },
                        threshold: null
                    }
                },

                series: [{
                    type: 'area',
                    name: JSON.parse('@Html.Raw(Json.Serialize(@Model.SensorType))'),
                    data: JSON.parse('@Html.Raw(Json.Serialize(@Model.Values))')

              }],
                exporting: {
            buttons: {
                contextButton: {
                    enabled: false,
                },
                }
        },
            });
        }
    );

    $('body').on('gsresizestop', '.grid-stack', function (event, ui) {
        var type = 'TimeSeries';
        try {
            var result = Highcharts.charts.find(chart => chart.renderTo.id == (type + ui.id).toString());
        }
        catch (error) {
            
        }
        if (typeof result !== 'undefined') {
            result.setSize(ui.height, ui.width);
        }
        
    });
</script>